Fix fail

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -53,6 +53,7 @@ get_variant() {
     Darwin)
       case "$(uname -m)" in
         x86_64) echo macos ;;
+        # arm64) echo macos-arm64 ;;
         *) fail "$(uname -m) is not supported on macos" ;;
       esac
       ;;
@@ -74,6 +75,13 @@ get_download_url() {
   local version=$1
   local variant=$(get_variant $version)
   echo "https://github.com/gleam-lang/gleam/releases/download/v${version}/gleam-v${version}-${variant}.tar.gz"
+}
+
+fail() {
+  error_message = $1
+  printf "$error_message\\n" 1>&2
+
+  return "1"
 }
 
 install_gleam $ASDF_INSTALL_TYPE $ASDF_INSTALL_VERSION $ASDF_INSTALL_PATH
